### ISSUE TITLE
extend import iso19139

### ISSUE THREAD

**Issue by pvgenuchten** [OSGeo/mdme#20]
currently picks up only 2 properties, should we implement more or delegate to a webservice which uses owslib or pygeometa to import the record?

**Comment by pvgenuchten** [comment]
alternatively, can I use the [metadata service provided by demo.pygeoapi.io](https://demo.pygeoapi.io/master/processes/pygeometa-metadata-generate) to convert iso19139 to mcf @tomkralidis? before loading it into mdme

**Comment by tomkralidis** [comment]
+1, makes sense.

**Comment by pvgenuchten** [comment]
I guess I should open a pr to pygeometa pygeoapi plug-in to include a method for importing metadata (to Mcf)?

**Comment by tomkralidis** [comment]
Sure/+1.  Feel free to open a [pygeometa issue](https://github.com/geopython/pygeometa/issues), as we could work on this at the OGC/OSGeo/ASF sprint.

**Comment by tomkralidis** [comment]
Update: this is already implemented in the pygeometa plugin code, and simply needed to be added to the https://demo.pygeoapi.io/master config (now done in https://github.com/geopython/demo.pygeoapi.io/commit/6620184185638322627b83b3029549dc02231380).

The demo containers should update shortly thereby making these functions available.

**Comment by pvgenuchten** [comment]
solved by #26
